### ISSUE TITLE
What is the input format of this script

### ISSUE THREAD

**Issue by xflicsu** [lvulliard/ExprCount2TPM#1]
This script is useful to calculate gene expression level (TPM)
So, what is the input format of this script?

**Comment by koalive** [comment]
The script takes the raw counts (hit per gene, not yet normalized by gene size or total hit count) as input. It has been developed for raw expression counts as offered on the Genomic Data Commons: plain text files with on each line the ENSEMBL gene identifier and the raw count, separated by a tabulation.
