### ISSUE TITLE
Nanopolish index step 

### ISSUE THREAD

**Issue by Caro-Ca** [lvulliard/ExprCount2TPM#4]
Hi!
I am analizyng long reads from Nanopore using Guppy basecalling data. I am in the nanopolish index step `(nanopolish index -d fast5_files/ reads.fasta)` and I don't understand why I am indexing if the output is not going to be used in the following steps. On the other hand, if nanopolish index is needed do you know any code that can fasten the runs?

Thank you for your help.

**Comment by koalive** [comment]
Hi,
This is definitely not the repository you are looking for, sorry.
Best regards.
